# fly.toml app configuration file generated for prime-checklist on 2025-06-14T17:34:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prime-checklist'
primary_region = 'gig'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
